// to-do-app/to-do-vue/src/views/user/PasswordUpdate.vue
<template>
    <div class="container-personal-info">
        <h2>Change My Password</h2>
        <div class="profile-info">
            <div class="label-field">
                <label class="label"> {{ userStore.user!.name }} {{ userStore.user!.lastName !== null ?
                    userStore.user!.lastName : '' }} </label>
            </div>
        </div>
        <hr />
        <div class="profile-form">
            <form @submit.prevent="updateMyPassword">
                <div class="label-field">
                    <label class="label">New Password</label>
                    <input v-model="password" type="password" required class="text-field">
                </div>
                <div>
                    <div class="div-submit-button">
                        <button type="submit" class="send-button">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div v-if="loading">
        <Loading />
    </div>

    <ErrorMessage :errorMessage="errorMessage" @on-close="closeErrorMessage" />
    <SuccessMessage :message="successMessage" @on-close="closeMessage" />
</template>

<script setup lang="ts">
import { getErrorMessage, getErrorMessageInputValues, getMessage, getMessageOperationSucceded } from '@/msg/messages';
import router from '@/router';
import { useUserStore } from '@/stores/user_store';
import { ref } from 'vue'
import { isPasswordInputValid } from '../validator/validator';
import Loading from '@/components/Loading.vue';
import ErrorMessage from '@/components/Error-message.vue';
import SuccessMessage from '@/components/Success-message.vue';

const userStore = useUserStore();
const loading = ref(false);
const errorMessage = ref('');
const successMessage = ref('');
const password = ref('');

const updateMyPassword = () => {
    if (!isFormValid()) {
        errorMessage.value = getErrorMessageInputValues();
    } else {
        loading.value = true;
        userStore.updateUserPassword(password.value)
            .then(() => {
                loading.value = false;
                successMessage.value = getMessageOperationSucceded();
            })
            .catch(err => {
                loading.value = false;
                handleError(err);
            })
    }
}

const handleError = (err: any) => {
    if (err.errorMessage) errorMessage.value = getMessage(err.errorMessage);
    else errorMessage.value = getErrorMessage();
}

const closeErrorMessage = () => {
    errorMessage.value = '';
}

const closeMessage = () => {
    successMessage.value = '';
    router.push('/');
}

const isFormValid = (): boolean => {
    return isPasswordInputValid(password.value)
}
</script>

<style scoped>
.container-personal-info {
    max-width: 90%;
    width: 630px;
    margin: 30px auto;
    height: 100%;
    padding: 30px;
}

.profile-info {
    margin: 10px 0;
}

hr {
    margin: 15px 7px;
}
</style>

// to-do-app/to-do-angular/src/app/view/user/password-update/password-update.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { getErrorMessage, getErrorMessageInputValues, getMessage, getMessageOperationSucceded } from 'src/app/msg/messages';
import { UserService } from 'src/app/service/user.service';
import { passwordValidation } from 'src/app/validator/validator';

@Component({
  selector: 'app-password-update',
  templateUrl: './password-update.component.html',
  styleUrls: ['./password-update.component.css']
})
export class PasswordUpdateComponent implements OnInit {

  formMyPassword: FormGroup = new FormGroup({
    "password": new FormControl('', [Validators.required, Validators.minLength(5), passwordValidation]),
  });

  loading: boolean = false;
  errorMessage: string = "";
  suscessMessage: string = "";
  firstName = "";
  lastName = "";

  constructor(private userService: UserService, private router: Router) { }

  ngOnInit(): void {
    this.firstName = this.userService.user.value!.name;
    this.lastName = this.userService.user.value!.lastName ? this.userService.user.value!.lastName! : "";
  }

  updateMyPassword() {
    if (this.formMyPassword.invalid) {
      this.errorMessage = getErrorMessageInputValues();
    } else {
      this.loading = true;
      this.userService.updateUserPassword(this.formMyPassword.get('password')!.value.trim()).subscribe({
        next: (userData) => {
          this.loading = false;
          this.suscessMessage = getMessageOperationSucceded();
        },
        error: (e) => { this.handleError(e); }
      });
    }
  }

  handleError(e: any) {
    console.log(e);
    this.loading = false;
    if (e.error && e.error.errorMessage) {
      this.errorMessage = getMessage(e.error.errorMessage);
    } else {
      this.errorMessage = getErrorMessage();
    }
  }

  closeErrorMessage() {
    this.errorMessage = "";
  }

  closeMessage() {
    this.suscessMessage = "";
    this.router.navigate(['/home/']);
  }

}
<div class="container-personal-info">
    <h2>Change My Password</h2>
    <div class="profile-info">
        <div class="label-field">
            <label class="label"> {{ firstName }} {{ lastName }} </label>
        </div>
    </div>
    <hr />
    <div class="profile-form">
        <form [formGroup]="formMyPassword" (submit)="updateMyPassword()">
            <div class="label-field">
                <label class="label">New Password</label>
                <input formControlName="password" type="password" required class="text-field">
                <p *ngIf="formMyPassword.get('password')!.invalid && formMyPassword.get('password')!.touched"
                    class="error-field-message">
                    Error on first name input.
                </p>
            </div>
            <div>
                <div class="div-submit-button">
                    <button [disabled]="formMyPassword.invalid" type="submit" class="send-button">Send</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div *ngIf="loading">
    <app-loading></app-loading>
</div>
<app-error-message [errorMessage]="errorMessage" (onClose)="closeErrorMessage()" />
<app-success-message [message]="suscessMessage" (onClose)="closeMessage()" />
