// to-do-app/to-do-vue/src/views/task/Lists.vue
<template>
    <div class="list-nav-container">
        <div class="title">
            <h3>My lists</h3>
            <button class="send-button" @click="newTaskList">New Task List</button>
        </div>
        <div v-if="taskStore.lists && taskStore.lists !== null && taskStore.lists.length > 0" class="my-task-lists">
            <hr class="solid">
            <ul>
                <li @click="showAllMyTasks">
                    <span>Show All Tasks</span>
                </li>
                <li @click="selectTaskList(taskList)" v-for="taskList in taskStore.lists">
                    <span>{{ taskList.listName }}</span>
                </li>
            </ul>
        </div>
    </div>
</template>

<script setup lang="ts">
import type { TaskList } from '@/model/task_list';
import { useTaskStore } from '@/stores/task_store';

const emit = defineEmits(['onNewTaskList', 'onShowAllTasks', 'onSelectTaskList']);
const taskStore = useTaskStore();

const newTaskList = () => {
    emit('onNewTaskList');
}

const showAllMyTasks = () => {
    emit('onShowAllTasks');
}

const selectTaskList = (taskList: TaskList) => {
    emit('onSelectTaskList', taskList);
}

</script>

<style scoped>
.list-nav-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
}

.title {
    width: 100%;
}

.title h3 {
    padding: 0 0 20px 0;
}

.title button {
    margin: 5px 10%;
    max-width: 80%;
}

.my-task-lists {
    margin-top: 20px;
    text-align: center;
    width: 100%;
}

.my-task-lists ul {
    list-style-type: none;
    width: 100%;
}

.my-task-lists ul li {
    width: 100%;
}

.my-task-lists ul li:hover span {
    background-color: rgba(215, 215, 215, 0.95);
    cursor: pointer;
}

.my-task-lists ul li span {
    padding: 8px;
    text-decoration: none;
    font-size: 18px;
    color: #A1A1A1;
    display: block;
    transition: 0.2s;
    width: 100%;
}

.my-task-lists ul li:hover span {
    color: #006698;
}
</style>

// to-do app/to-do-ang/src/app/view/tasks/lists/lists.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { TaskList } from 'src/app/model/taskList';

@Component({
  selector: 'app-lists',
  templateUrl: './lists.component.html',
  styleUrls: ['./lists.component.css']
})
export class ListsComponent implements OnInit {

  @Input() taskLists: TaskList[] | null = null;
  @Output() onSelectTaskList: EventEmitter<TaskList> = new EventEmitter();
  @Output() onShowAllTasks: EventEmitter<any> = new EventEmitter();
  @Output() onNewTaskList: EventEmitter<any> = new EventEmitter();

  ngOnInit(): void {
      
  }

  newTaskList() {
    this.onNewTaskList.emit();
  }

  showAllMyTasks() {
    this.onShowAllTasks.emit();
  }

  selectTaskList(taskList: TaskList) {
    this.onSelectTaskList.emit(taskList);
  }

}

<div class="list-nav-container">
    <div class="title">
        <h3>My lists</h3>
        <button class="send-button" (click)="newTaskList()">New Task List</button>
    </div>
    <div *ngIf="taskLists && taskLists !== null && taskLists.length > 0" class="my-task-lists">
        <hr class="solid">
        <ul>
            <li (click)="showAllMyTasks()">
                <span>Show All Tasks</span>
            </li>
            <li (click)="selectTaskList(taskList)" *ngFor="let taskList of taskLists; index as i">
                <span>{{ taskList.listName }}</span>
            </li>
        </ul>
    </div>
</div>
