// to-do-app/to-do-angular/src/app/view/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators, ValidationErrors } from '@angular/forms';
import { Router } from '@angular/router';
import { STATUS_ACTIVE, UserData } from 'src/app/model/user';
import { getErrorMessage, getErrorMessageInputValues, getMessage } from 'src/app/msg/messages';
import { UserService } from 'src/app/service/user.service';
import { passwordValidation } from 'src/app/validator/validator';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  formLogin: FormGroup = new FormGroup({
    "email": new FormControl('', [Validators.email, Validators.required]),
    "password": new FormControl('', [Validators.required, passwordValidation]),
  });

  loading: boolean = false;
  errorMessage: string = "";

  constructor(private userService: UserService, private router: Router) { }

  ngOnInit(): void {
      if (this.userService.isUserLoggedIn()) {
        this.router.navigate(['/']);
      }
  }

  closeErrorMessage() {
    this.errorMessage = "";
  }

  login() {
    if (this.formLogin.invalid) {
      this.errorMessage = getErrorMessageInputValues();
    } else {
      this.loading = true;
      this.userService.login(this.formLogin.get('email')!.value.trim(), this.formLogin.get('password')!.value.trim()).subscribe({
        next: (userData) => { 
          this.loading = false; 
          this.userLoginHandler(userData as UserData) 
        },
        error: (err) => {
          this.loading = false;
          this.handleError(err);
        }
      });
    }
  }

  userLoginHandler(userData: UserData) {
    this.loading = false;
    if ((userData).status === STATUS_ACTIVE) {
      this.router.navigate(['/']);
    } else {
      this.router.navigate(['/useractivationrequest/' + this.formLogin.get('email')!.value.trim()]);
    }
  }

  handleError(e: any) {
    console.log(e);
    if (e.error && e.error.errorMessage) {
      if (e.error.errorMessage === "MSE07") { this.router.navigate(['/useractivationrequest/' + this.formLogin.get('email')!.value.trim()]); }
      else { this.errorMessage = getMessage(e.error.errorMessage); }
    } else {
      this.errorMessage = getErrorMessage();
    }
  }


}

// to-do-app/to-do-vue/src/views/auth/Login.vue
<template>
    <div class="container-auth">
    <div class="card-auth">
        <div class="logo">
            <a><img src="../../assets/logo.png">
                <h3>My Task List</h3>
            </a>
        </div>
        <h2>Login</h2>
        <form @submit.prevent="login">
            <div class="label-field">
                <label class="label">E-mail</label>
                <input type="email" v-model="email" required class="text-field">
                <!-- <p *ngIf="formLogin.get('email')!.invalid && formLogin.get('email')!.touched"
                    class="error-field-message">
                    Error on e-mail input.
                </p> -->
            </div>
            <div class="label-field">
                <label class="label">Password</label>
                <input type="password" v-model="password" required class="text-field">
                <!-- <p *ngIf="formLogin.get('password')!.invalid && formLogin.get('password')!.touched"
                    class="error-field-message">
                    Error on password input.
                </p> -->
            </div>
            <div>
                <div class="div-submit-button">
                    <button type="submit" class="send-button">Send</button>
                </div>
                <div class="action-links">
                    <router-link to="/recoverpassword">Forgot password?</router-link>
                    <router-link to="/userregistration">New user?, Register here</router-link>
                </div>
            </div>
        </form>
    </div>
</div>

<div v-if="loading">
    <Loading/>
</div>

<ErrorMessage :errorMessage="errorMessage" @on-close="closeErrorMessage"/>
</template>

<script setup lang="ts">

import { getErrorMessage, getErrorMessageInputValues, getMessage } from '@/msg/messages';
import router from '@/router';
import { useUserStore } from '@/stores/user_store';
import { ref } from 'vue'
import { isEmailValid, isPasswordInputValid } from '../validator/validator';
import Loading from '@/components/Loading.vue';
import ErrorMessage from '@/components/Error-message.vue';

const userStore = useUserStore();
const loading = ref(false);
const errorMessage = ref('');
const email = ref('');
const password = ref('');

const login = () => {
    if (!isFormValid()) {
        errorMessage.value = getErrorMessageInputValues()
    } else {
        loading.value = true;
        userStore.login(email.value.trim().toLocaleLowerCase(), password.value.trim())
            .then(() => {
                loading.value = false;
                router.push({name: 'home'})
            })
            .catch(err => {
                loading.value = false;
                handleError(err);
            })
    }
}

const handleError = (err: any) => {
    if (err.errorMessage) {
        if (err.errorMessage === "MSE07") {
            router.push({ name: 'useractivationrequest', params: { email: email.value } })
        }
        else { errorMessage.value = getMessage(err.errorMessage); }
    } else {
        errorMessage.value = getErrorMessage();
    }
}

const closeErrorMessage = () => {
    errorMessage.value = '';
}

const isFormValid = (): boolean => {
    return isEmailValid(email.value) && isPasswordInputValid(password.value)
}

</script>

<style scoped></style>
