// to-do-app/to-do-angular/src/app/view/auth/new-user/new-user.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators, ValidationErrors } from '@angular/forms';
import { Router } from '@angular/router';
import { getErrorMessage, getErrorMessageInputValues, getMessage } from 'src/app/msg/messages';
import { UserService } from 'src/app/service/user.service';
import { passwordValidation } from 'src/app/validator/validator';

@Component({
  selector: 'app-new-user',
  templateUrl: './new-user.component.html',
  styleUrls: ['./new-user.component.css']
})
export class NewUserComponent {

  formUserRegistration: FormGroup = new FormGroup({
    "email": new FormControl('', [Validators.email, Validators.required]),
    "password": new FormControl('', [Validators.required, Validators.minLength(5), passwordValidation]),
    "name": new FormControl('', Validators.required),
    "lastName": new FormControl(null),
  });

  loading: boolean = false;
  errorMessage: string = "";

  constructor(private userService: UserService, private router: Router) { }

  registerUser() {
    this.errorMessage = "";
    if (this.formUserRegistration.get('email')!.invalid || this.formUserRegistration.get('password')!.invalid || this.formUserRegistration.get('name')!.invalid) {
      this.errorMessage = getErrorMessageInputValues();
    } else {
      this.loading = true;
      this.userService.registerUser(
          this.formUserRegistration.get('email')!.value.trim(), 
          this.formUserRegistration.get('password')!.value.trim(),
          this.formUserRegistration.get('name')!.value.trim(),
          this.formUserRegistration.get('lastName') != null ? this.formUserRegistration.get('lastName')!.value.trim() : ''
          )
          .subscribe({
            next: (data) => {
              this.loading = false;
              this.router.navigate(['/useractivation/' + this.formUserRegistration.get('email')!.value.trim()]);
            },
            error: (e) => {
              this.loading = false;
              if (e.error && e.error.errorMessage) { this.errorMessage = getMessage(e.error.errorMessage); }
              else { this.errorMessage = getErrorMessage(); }
            }
      });
    }
  }

  closeErrorMessage() {
    this.errorMessage = "";
  }

}
<div class="container-auth">
    <div class="card-auth">
        <div class="logo">
            <a><img src="../../../assets/logo.png">
                <h3>My Task List</h3>
            </a>
        </div>
        <h2>User Registration</h2>
        <form [formGroup]="formUserRegistration" (submit)="registerUser()">
            <div class="label-field">
                <label class="label">E-mail</label>
                <input formControlName="email" type="email" required class="text-field">
                <p *ngIf="formUserRegistration.get('email')!.invalid && formUserRegistration.get('email')!.touched"
                    class="error-field-message">
                    Error on e-mail input.
                </p>
            </div>
            <div class="label-field">
                <label class="label">Password</label>
                <input formControlName="password" type="password" required class="text-field">
                <p *ngIf="formUserRegistration.get('password')!.invalid && formUserRegistration.get('password')!.touched"
                    class="error-field-message">
                    Error on password input.
                </p>
            </div>
            <div class="label-field">
                <label class="label">Name</label>
                <input formControlName="name" type="text" required class="text-field">
                <p *ngIf="formUserRegistration.get('name')!.invalid && formUserRegistration.get('name')!.touched"
                    class="error-field-message">
                    Error on name input.
                </p>
            </div>
            <div class="label-field">
                <label class="label">Last Name</label>
                <input formControlName="lastName" type="text" required class="text-field">
            </div>
            <div>
                <div class="div-submit-button">
                    <button [disabled]="formUserRegistration.get('email')!.invalid || formUserRegistration.get('password')!.invalid || formUserRegistration.get('name')!.invalid" type="submit" class="send-button">Send</button>
                </div>
                <div class="action-links">
                    <a class="side-link" routerLink="/recoverpassword">Forgot password?</a>
                    <a class="side-link" routerLink="/login">Make Login</a>
                </div>
            </div>
        </form>
    </div>
</div>

<div *ngIf="loading">
    <app-loading></app-loading>
</div>
<app-error-message [errorMessage]="errorMessage" (onClose)="closeErrorMessage()" />

// to-do-app/to-do-vue/src/views/auth/New-User.vue
<template>
    <div class="container-auth">
        <div class="card-auth">
            <div class="logo">
                <a><img src="../../assets/logo.png">
                    <h3>My Task List</h3>
                </a>
            </div>
            <h2>User Registration</h2>
            <form @submit.prevent="registerUser">
                <div class="label-field">
                    <label class="label">E-mail</label>
                    <input v-model="email" type="email" required class="text-field">
                </div>
                <div class="label-field">
                    <label class="label">Password</label>
                    <input v-model="password" type="password" required class="text-field">
                </div>
                <div class="label-field">
                    <label class="label">Name</label>
                    <input v-model="name" type="text" required class="text-field">
                </div>
                <div class="label-field">
                    <label class="label">Last Name</label>
                    <input v-model="lastName" type="text" required class="text-field">
                </div>
                <div>
                    <div class="div-submit-button">
                        <button type="submit" class="send-button">Send</button>
                    </div>
                    <div class="action-links">
                        <router-link class="side-link" to="/recoverpassword">Forgot password?</router-link>
                        <router-link class="side-link" to="/login">Make Login</router-link>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div v-if="loading">
        <Loading />
    </div>

    <ErrorMessage :errorMessage="errorMessage" @on-close="closeErrorMessage" />
</template>

<script setup lang="ts">
import { getErrorMessage, getErrorMessageInputValues, getMessage } from '@/msg/messages';
import router from '@/router';
import { useUserStore } from '@/stores/user_store';
import { ref } from 'vue'
import { isEmailValid, isPasswordInputValid } from '../validator/validator';
import Loading from '@/components/Loading.vue';
import ErrorMessage from '@/components/Error-message.vue';

const userStore = useUserStore();
const loading = ref(false);
const errorMessage = ref('');
const email = ref('');
const password = ref('');
const name = ref('');
const lastName = ref('');

const registerUser = () => {
    if (!isFormValid()) {
        errorMessage.value = getErrorMessageInputValues()
    } else {
        loading.value = true;
        userStore.registerUser(email.value.trim().toLocaleLowerCase(), password.value.trim(), name.value.trim(), lastName.value.trim())
            .then(() => {
                loading.value = false;
                router.push({ name: 'useractivation', params: { email: email.value } })
            })
            .catch(err => {
                loading.value = false;
                handleError(err);
            })
    }
}

const handleError = (err: any) => {
    if (err.errorMessage) {
        if (err.errorMessage === "MSE07") {
            router.push({ name: 'useractivationrequest', params: { email: email.value } })
        }
        else { errorMessage.value = getMessage(err.errorMessage); }
    } else {
        errorMessage.value = getErrorMessage();
    }
}

const closeErrorMessage = () => {
    errorMessage.value = '';
}

const isFormValid = (): boolean => {
    return isEmailValid(email.value)
        && isPasswordInputValid(password.value)
        && name.value != null && name.value.trim().length > 0
}

</script>

<style scoped>
.container-auth .card-auth {
    margin: auto;
}
</style>
