// to-do app/to-do-ang/src/app/view/auth/reset-password/reset-password.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { getErrorMessageInputValues, getMessage } from 'src/app/message/message';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-reset-password',
  templateUrl: './reset-password.component.html',
  styleUrls: ['./reset-password.component.css']
})
export class ResetPasswordComponent implements OnInit {

  email: string = this.route.snapshot.params['email'];
  loading: boolean = false;
  errorMessage: string = "";
  formPasswordReset: FormGroup = new FormGroup({
    "email": new FormControl(this.email, [Validators.required, Validators.email]),
    "newPasswordCode": new FormControl('', [Validators.required, Validators.minLength(6), Validators.maxLength(6)]),
    "newPassword": new FormControl('', [Validators.required, this.userService.passwordValidation]),
  });

  constructor(private userService: UserService, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    if (this.email === "" || this.userService.isUserLoggedIn()) {
      this.router.navigate(['/']);
    } else {
      this.formPasswordReset.value.email = this.email
    }
  }

  resetPassword() {
    this.formPasswordReset.value.email = this.email
    if (!this.email || this.formPasswordReset.invalid) {
      this.errorMessage = getErrorMessageInputValues();
      return;
    }
    this.loading = true;
    this.userService.registerNerPasswordFromCode(this.email, this.formPasswordReset.value.newPassword, this.formPasswordReset.value.newPasswordCode).subscribe(
      response => {
        console.log(response);
        this.loading = false;
        this.router.navigate(['/']);
      },
      err => {
        console.log(err);
        this.loading = false;
        this.errorMessage = getMessage(err.errorMessage)
      }
    )
  }

  closeErrorMessage() {
    this.errorMessage = "";
  }

}
<div class="container-auth">
    <div class="card-auth">
        <div class="logo">
            <a><img src="../../../assets/logo.png">
                <h3>My Task List</h3>
            </a>
        </div>
        <h2>User Activation</h2>
        <form [formGroup]="formPasswordReset" (submit)="resetPassword()">
            <div class="label-field">
                <label class="label">E-mail:   {{ formPasswordReset.get('email')!.value }} </label>
            </div>
            <div class="label-field">
                <label class="label">New Password Code</label>
                <input formControlName="newPasswordCode" type="text" required class="text-field">
                <p *ngIf="formPasswordReset.get('newPasswordCode')!.invalid && formPasswordReset.get('newPasswordCode')!.touched"
                    class="error-field-message">
                    Error on new password code input.
                </p>
            </div>
            <div class="label-field">
                <label class="label">New Password</label>
                <input formControlName="newPassword" type="password" required class="text-field">
                <p *ngIf="formPasswordReset.get('newPassword')!.invalid && formPasswordReset.get('newPassword')!.touched"
                    class="error-field-message">
                    Error on password input.
                </p>
            </div>
            <div>
                <div class="div-submit-button">
                    <button [disabled]="formPasswordReset.invalid" type="submit" class="send-button">Send</button>
                </div>
                <div class="action-links">
                    <a class="side-link" routerLink="/userregistration">New user?, Register here</a>
                    <a class="side-link" routerLink="/login">Make Login</a>
                </div>
            </div>
        </form>
    </div>
</div>

<div *ngIf="loading">
    <app-loading></app-loading>
</div>
<app-error-message [errorMessage]="errorMessage" (onClose)="closeErrorMessage()" />

// to-do-app/to-do-vue/src/views/auth/Reset-password.vue
<template>
    <div class="container-auth">
        <div class="card-auth">
            <div class="logo">
                <a><img src="../../assets/logo.png">
                    <h3>My Task List</h3>
                </a>
            </div>
            <h2>Password Reset</h2>
            <form @submit.prevent="resetPassword">
                <div class="label-field">
                    <label class="label">E-mail: {{ email }} </label>
                </div>
                <div class="label-field">
                    <label class="label">New Password Code</label>
                    <input v-model="newPasswordCode" type="text" required class="text-field">
                </div>
                <div class="label-field">
                    <label class="label">New Password</label>
                    <input v-model="newPassword" type="password" required class="text-field">
                </div>
                <div>
                    <div class="div-submit-button">
                        <button type="submit" class="send-button">Send</button>
                    </div>
                    <div class="action-links">
                        <router-link class="side-link" to="/userregistration">New user?, Register here</router-link>
                        <router-link class="side-link" to="/login">Make Login</router-link>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div v-if="loading">
        <Loading />
    </div>

    <ErrorMessage :errorMessage="errorMessage" @on-close="closeErrorMessage" />
</template>

<script setup lang="ts">
import { getErrorMessage, getErrorMessageInputValues, getMessage } from '@/msg/messages';
import router from '@/router';
import { useUserStore } from '@/stores/user_store';
import { ref } from 'vue'
import { isEmailValid, isPasswordInputValid } from '../validator/validator';
import { LENGTH_NEW_PASSWORD_CODE } from '../../consts/consts'
import Loading from '@/components/Loading.vue';
import ErrorMessage from '@/components/Error-message.vue';
import { useRoute } from 'vue-router';

const route = useRoute()
const userStore = useUserStore();
const loading = ref(false);
const errorMessage = ref('');
const email = route.params.email.toString()
const newPassword = ref('');
const newPasswordCode = ref('');

const resetPassword = () => {
    if (!isFormValid()) {
        errorMessage.value = getErrorMessageInputValues()
    } else {
        loading.value = true;
        userStore.registerNerPasswordFromCode(email, newPassword.value.trim(), newPasswordCode.value.trim())
            .then(() => {
                loading.value = false;
                router.push({name: 'taskview'});
            })
            .catch(err => {
                loading.value = false;
                handleError(err);
            })
    }
}

const handleError = (err: any) => {
    if (err.errorMessage) {
        if (err.errorMessage === "MSE07") {
            router.push({ name: 'useractivationrequest', params: { email: email } })
        }
        else { errorMessage.value = getMessage(err.errorMessage); }
    } else {
        errorMessage.value = getErrorMessage();
    }
}

const closeErrorMessage = () => {
    errorMessage.value = '';
}

const isFormValid = (): boolean => {
    return isEmailValid(email)
        && newPasswordCode.value.trim().length === LENGTH_NEW_PASSWORD_CODE
        && isPasswordInputValid(newPassword.value)
}

</script>

<style scoped></style>
