// to-do-app/to-do-vue/src/views/auth/Forget-password.vue
<template>
    <div class="container-auth">
        <div class="card-auth">
            <div class="logo">
                <a><img src="../../assets/logo.png">
                    <h3>My Task List</h3>
                </a>
            </div>
            <h2>Forget your password</h2>
            <p>Tell us your e-mail to recover your password</p>
            <form @submit.prevent="sendRequest">
                <div class="label-field">
                    <label class="label">E-mail</label>
                    <input v-model="email" type="email" required class="text-field">
                </div>
                <div>
                    <div class="div-submit-button">
                        <button type="submit" class="send-button">Send</button>
                    </div>
                    <div class="action-links">
                        <router-link class="side-link" to="/userregistration">New user?, Register here</router-link>
                        <router-link class="side-link" to="/login">Make Login</router-link>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div v-if="loading">
        <Loading />
    </div>

    <ErrorMessage :errorMessage="errorMessage" @on-close="closeErrorMessage" />
</template>

<script setup lang="ts">
import { getErrorMessage, getErrorMessageInputValues, getMessage } from '@/msg/messages';
import router from '@/router';
import { useUserStore } from '@/stores/user_store';
import { ref } from 'vue'
import { isEmailValid } from '../validator/validator';
import Loading from '@/components/Loading.vue';
import ErrorMessage from '@/components/Error-message.vue';

const userStore = useUserStore();
const loading = ref(false);
const errorMessage = ref('');
const email = ref('');

const sendRequest = () => {
    if (!isFormValid()) {
        errorMessage.value = getErrorMessageInputValues()
    } else {
        loading.value = true;
        userStore.forgotPassword(email.value.trim().toLocaleLowerCase())
            .then(() => {
                loading.value = false;
                router.push({ name: 'passwordreset', params: { email: email.value } })
            })
            .catch(err => {
                loading.value = false;
                handleError(err);
            })
    }
}

const handleError = (err: any) => {
    if (err.errorMessage) {
        if (err.errorMessage === "MSE07") {
            router.push({ name: 'useractivationrequest', params: { email: email.value } })
        }
        else { errorMessage.value = getMessage(err.errorMessage); }
    } else {
        errorMessage.value = getErrorMessage();
    }
}

const closeErrorMessage = () => {
    errorMessage.value = '';
}

const isFormValid = (): boolean => {
    return isEmailValid(email.value)
}

</script>

<style scoped>
.card-auth p {
    margin: 0 0 15px 0;
}
</style>

// to-do app/to-do-angular/src/app/view/auth/forgetpassword/forgetpassword.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { getErrorMessage, getErrorMessageInputValues, getMessage } from 'src/app/message/message';
import { AuthService } from 'src/app/service/auth.service';

@Component({
  selector: 'app-forgetpassword',
  templateUrl: './forgetpassword.component.html',
  styleUrls: ['./forgetpassword.component.css']
})
export class ForgetpasswordComponent implements OnInit {

  formForgetPassword: FormGroup = new FormGroup({
    "email": new FormControl('', [Validators.email, Validators.required]),
  });

  loading: boolean = false;
  errorMessage: string = "";

  constructor(private authService: AuthService, private router: Router) { }

  ngOnInit(): void {
    if (this.authService.isUserLoggedIn()) {
      this.router.navigate(['/']);
    }
  }

  closeErrorMessage() {
    this.errorMessage = "";
  }

  sendRequest() {
    this.errorMessage = "";
    if (this.formForgetPassword.invalid) {
      this.errorMessage = getErrorMessageInputValues();
    } else {
      this.loading = true;
      this.authService.forgotPassword(this.formForgetPassword.get('email')!.value.trim()).subscribe({
        next: (data) => {
          console.log(data);
          this.loading = false;
          this.router.navigate(['/passwordreset/' + this.formForgetPassword.get('email')!.value.trim()]);
        },
        error: (e) => {
          console.log(e);
          this.loading = false;
          if (e.error && e.error.errorMessage) { this.errorMessage = getMessage(e.error.errorMessage); }
          else { this.errorMessage = getErrorMessage(); }
        }
      });
    }
  }



}

<div class="container">
    <div class="card-form">
        <h2>Forget your password</h2>
        <p>Tell us your e-mail to recover your password</p>
        <form [formGroup]="formForgetPassword" (submit)="sendRequest()">
            <div class="label-field">
                <label class="label">E-mail: </label>
                <input formControlName="email" type="email" required class="text-field">
                <p *ngIf="formForgetPassword.get('email')!.invalid && formForgetPassword.get('email')!.touched"
                    class="error-field-message">
                    Error on e-mail input.
                </p>
            </div>
            <div>
                <div class="div-submit-button">
                    <button [disabled]="formForgetPassword.invalid" type="submit" class="send-button">Send</button>
                </div>
                <div class="div-submit-button-auth">
                    <a class="side-link" routerLink="/userregistration">New user?, Register here</a>
                    <a class="side-link" routerLink="/login">Make Login</a>
                </div>
            </div>
        </form>
    </div>
</div>

<div *ngIf="loading">
    <app-loading></app-loading>
</div>
<app-error-message [errorMessage]="errorMessage" (onClose)="closeErrorMessage()" />
