// to-do-app/to-do-vue/src/views/task/ListEdit.vue
<template>
    <div class="task-form">
        <h2>Task List</h2>
        <form @submit.prevent="save">
            <div class="label-field">
                <label class="label">List Name</label>
                <input v-model="listName" type="text" required class="text-field">
            </div>
            <div class="label-field">
                <label class="label">List Description</label>
                <textarea v-model="listDescription" class="textarea"></textarea>
            </div>
            <div class="div-submit-button">
                <button type="button" @click="cancel" class="action-button">Cancel</button>
                <button type="submit" class="action-button">Send</button>
            </div>
        </form>
    </div>

    <div v-if="loading">
        <Loading />
    </div>

    <ErrorMessage :errorMessage="errorMessage" @on-close="closeErrorMessage" />
</template>
<script setup lang="ts">
import Loading from '@/components/Loading.vue';
import ErrorMessage from '@/components/Error-message.vue';
import { ref } from 'vue';
import { getErrorMessage, getErrorMessageInputValues, getMessage } from '@/msg/messages';
import router from '@/router';
import { useTaskStore } from '@/stores/task_store';
import { useRoute } from 'vue-router';

const loading = ref(false);
const errorMessage = ref('');
const listName = ref('');
const listDescription = ref('');
const route = useRoute();
const id = route.params.id.toString();

const taskStore = useTaskStore();

const checkIfIsEditingList = () => {
    if (id !== "new") {
        const idList = Number(id);
        if (idList && !isNaN(idList)) {
            const currentList = taskStore.getListById(idList);
            if (currentList == null) {
                router.push({ name: 'not-found' });
            } else {
                listName.value = currentList.listName;
                listDescription.value = currentList.listDescription;
            }
        } else {
            router.push({ name: 'not-found' });
        }
    }
}

checkIfIsEditingList();

const save = () => {
    if (listName.value.trim().length <= 0) {
        errorMessage.value = getErrorMessageInputValues();
    } else {
        const idList = Number(id);
        if (idList && !isNaN(idList)) {
            saveListEdited(idList);
        } else {
            saveNewList();
        }
    }
}

const saveNewList = () => {
    loading.value = true;
    taskStore.createTaskList(listName.value.trim(), listDescription.value.trim())
        .then(() => {
            loading.value = false;
            router.push('/');
        })
        .catch(err => {
            loading.value = false;
            handleError(err);
        })
}

const saveListEdited = (idList: number) => {
    loading.value = true;
    taskStore.updateTaskList(listName.value.trim(), listDescription.value.trim(), idList)
        .then(() => {
            loading.value = false;
            router.push('/');
        })
        .catch(err => {
            loading.value = false;
            handleError(err);
        })
}

const cancel = () => {
    router.push('/');
}

const handleError = (err: any) => {
    if (err.errorMessage) errorMessage.value = getMessage(err.errorMessage);
    else errorMessage.value = getErrorMessage();
}

const closeErrorMessage = () => {
    errorMessage.value = '';
}

</script>
<style scoped></style>

// to-do-app/to-do-angular/src/app/view/task/list-edit/list-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { TaskList } from 'src/app/model/taskList';
import { getErrorMessage, getErrorMessageInputValues, getMessage } from 'src/app/msg/messages';
import { TaskService } from 'src/app/service/task.service';

@Component({
  selector: 'app-list-edit',
  templateUrl: './list-edit.component.html',
  styleUrls: ['./list-edit.component.css']
})
export class ListEditComponent implements OnInit {

  id: number | null = this.route.snapshot.params['id'];
  loading: boolean = false;
  errorMessage: string = "";

  formTaskList: FormGroup = new FormGroup({
    "listName": new FormControl('', [Validators.required]),
    "listDescription": new FormControl(''),
  });

  constructor(private router: Router, private route: ActivatedRoute, private taskService: TaskService) { }

  ngOnInit(): void {
    if (this.id !== null && this.id > 0) {
      let list: TaskList | null = this.getList(this.id);
      if (list != null) {
        this.formTaskList.patchValue({
          'listName': list.listName,
          'listDescription': list.listDescription
        });
      }
    }
  }

  getList(id: number): TaskList | null {
    return this.taskService.getList(id);
  }

  cancel() {
    this.id = null;
    this.formTaskList.reset();
    this.router.navigate(['/home/']);
  }

  save() {
    if (this.formTaskList.invalid) {
      this.errorMessage = getErrorMessageInputValues();
    } else {
      this.loading = true;
      let subscription;
      if (this.id && this.id !== null && this.id > 0) {
        subscription = this.taskService.updateTaskList(this.formTaskList.value.listName, this.formTaskList.value.listDescription, this.id);
      } else {
        subscription = this.taskService.createTaskList(this.formTaskList.value.listName, this.formTaskList.value.listDescription);
      }
      subscription.subscribe({
        next: (newTaskList) => {
          if (newTaskList && newTaskList !== null) {
            this.taskService.selectTaskList(newTaskList as TaskList);
          }
          this.loading = false;
          this.router.navigate(['/home/']);

        },
        error: (e) => { this.handleError(e) }
      });
    }
  }

  handleError(e: any) {
    this.loading = false;
    if (e.error && e.error.errorMessage) {
      this.errorMessage = getMessage(e.error.errorMessage);
    } else {
      this.errorMessage = getErrorMessage();
    }
  }

  closeErrorMessage() {
    this.errorMessage = "";
  }

}

<div class="task-form">
    <h2>Task List</h2>
    <form [formGroup]="formTaskList" (submit)="save()">
        <div class="label-field">
            <label class="label">List Name</label>
            <input formControlName="listName" type="text" required class="text-field">
            <p *ngIf="formTaskList.get('listName')!.invalid && formTaskList.get('listName')!.touched"
                class="error-field-message">
                Error on list name input.
            </p>
        </div>
        <div class="label-field">
            <label class="label">List Description</label>
            <textarea formControlName="listDescription" class="textarea"></textarea>
        </div>
        <div class="div-submit-button">
            <button type="button" (click)="cancel()" class="action-button">Cancel</button>
            <button [disabled]="formTaskList.invalid" type="submit" class="action-button">Send</button>
        </div>
    </form>
</div>


<div *ngIf="loading">
    <app-loading></app-loading>
</div>

<app-error-message [errorMessage]="errorMessage" (onClose)="closeErrorMessage()" />
